function [period, period_len] = find_period(bitStream, bitCap)
    % Inputs:
    % bitStream: The random number data out bitstream generated by the LSFR
    % bitCap: The number of bits used for the LSFR

    % Output:
    % period: The vector containing the period
    % period_len: The length of the period

    % strfind() finds all occurrences of a sequence in another sequence and
    % returns a vector containing all indexes where there is a match. We
    % use this to find where the first sequence of length bitCap numbers 
    % start to repeat.
    occurences = strfind(bitStream, bitStream(1:bitCap));
    period_len = occurences(2)-occurences(1);
    period = bitStream(occurences(1):occurences(2)-1);
end