function write_period_stream(filename, bitStream)
    % Inputs:
    % filename: The name of the file to write to
    % bitStream: The random number data out bitstream generated by the LSFR
    
    % Convert the bitstream into a sequence of bytes
    bitStreamBytes = bit_array_to_bytes(bitStream);
    
    % Write the bytes into the file
    fid = fopen(filename, 'w');
    for i = 1:16:size(bitStreamBytes, 2)
        if size(bitStreamBytes, 2) - i < 16
            fprintf(fid, '%3g, ', bitStreamBytes(i:end));
        else
            fprintf(fid, '%3g, ', bitStreamBytes(i:i+15));
            fprintf(fid, '\n');
        end
    end
    % Close the file
    fclose(fid);
end
